### ISSUE TITLE
[BUG] Could not Download the Series

### ISSUE THREAD

**Issue by shedowe19** [speedyconzales/series-scraper#3]
C:\Users\Shedowe\Downloads\Compressed\series-scraper-main>python main.py serie https://bs.to/serie/Pok-mon-Horizons-The-Series-Pokemon-2023 Deutsch
INFO - 2024-04-29 18:41:53,244 - main.py -> ------------- Series-Scraper started ------------
INFO - 2024-04-29 18:41:53,430 - main.py -> Season 1 has 47 Episodes.
Traceback (most recent call last):
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\main.py", line 47, in check_episodes
    episode_link = get_episode_link(url, language, provider, season, episode, burning_series)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\src\html_scraper.py", line 37, in get_episode_link
    link_to_episode = find_bs_link_to_episode(link_to_episode, provider)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\src\html_scraper.py", line 105, in find_bs_link_to_episode
    video_in_media_provider = WebDriverWait(driver, 0).until(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x0122C113+48259]
        (No symbol) [0x011BCA41]
        (No symbol) [0x010B0A17]
        (No symbol) [0x010F0BED]
        (No symbol) [0x010F0C9B]
        (No symbol) [0x0112BC12]
        (No symbol) [0x01110DE4]
        (No symbol) [0x01129B9C]
        (No symbol) [0x01110B36]
        (No symbol) [0x010E570D]
        (No symbol) [0x010E62CD]
        GetHandleVerifier [0x014E6533+2908323]
        GetHandleVerifier [0x01523B4B+3159739]
        GetHandleVerifier [0x012C505B+674763]
        GetHandleVerifier [0x012CB21C+699788]
        (No symbol) [0x011C6244]
        (No symbol) [0x011C2298]
        (No symbol) [0x011C242C]
        (No symbol) [0x011B4BB0]
        BaseThreadInitThunk [0x75927BA9+25]
        RtlInitializeExceptionChain [0x7720BE3B+107]
        RtlClearBits [0x7720BDBF+191]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\main.py", line 127, in <module>
    main()
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\main.py", line 100, in main
    pending_episodes, language_episodes, future_list = check_episodes(
                                                       ^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\main.py", line 54, in check_episodes
    except [HTTPError, URLError] as message:
TypeError: catching classes that do not inherit from BaseException is not allowed
Exception ignored in: <function Chrome.__del__ at 0x000001E22F2898A0>
Traceback (most recent call last):
  File "C:\Users\Shedowe\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\Shedowe\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] Das Handle ist ungültig

C:\Users\Shedowe\Downloads\Compressed\series-scraper-main>

**Comment by speedyconzales** [comment]
make sure you are using a virtual environment in which you are installing the required python packages to avoid versioning issues of the dependencies
AND 
please stick to python3.11 as python3.12 is not working -> I will update the README to emphasize this

**Comment by shedowe19** [comment]
(venv) C:\Users\Shedowe\Downloads\Compressed\series-scraper-main>pip install -r requirements.txt
Collecting attrs==23.2.0 (from -r requirements.txt (line 2))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 3))
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting certifi==2024.2.2 (from -r requirements.txt (line 4))
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 5))
  Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting h11==0.14.0 (from -r requirements.txt (line 6))
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting idna==3.7 (from -r requirements.txt (line 7))
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting outcome==1.3.0.post0 (from -r requirements.txt (line 8))
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting pysocks==1.7.1 (from -r requirements.txt (line 9))
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting pyyaml==6.0.1 (from -r requirements.txt (line 10))
  Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Collecting requests==2.31.0 (from -r requirements.txt (line 11))
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting selenium==4.20.0 (from -r requirements.txt (line 12))
  Downloading selenium-4.20.0-py3-none-any.whl.metadata (6.9 kB)
Collecting sniffio==1.3.1 (from -r requirements.txt (line 13))
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting sortedcontainers==2.4.0 (from -r requirements.txt (line 14))
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting soupsieve==2.5 (from -r requirements.txt (line 15))
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting trio==0.25.0 (from -r requirements.txt (line 16))
  Using cached trio-0.25.0-py3-none-any.whl.metadata (8.7 kB)
Collecting trio-websocket==0.11.1 (from -r requirements.txt (line 17))
  Using cached trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Collecting typing-extensions==4.11.0 (from -r requirements.txt (line 18))
  Downloading typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting undetected-chromedriver==3.5.5 (from -r requirements.txt (line 19))
  Using cached undetected-chromedriver-3.5.5.tar.gz (65 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting urllib3==2.2.1 (from urllib3[socks]==2.2.1->-r requirements.txt (line 20))
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting websockets==12.0 (from -r requirements.txt (line 21))
  Downloading websockets-12.0-cp311-cp311-win_amd64.whl.metadata (6.8 kB)
Collecting wsproto==1.2.0 (from -r requirements.txt (line 22))
  Using cached wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Collecting cffi>=1.14 (from trio==0.25.0->-r requirements.txt (line 16))
  Downloading cffi-1.16.0-cp311-cp311-win_amd64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.14->trio==0.25.0->-r requirements.txt (line 16))
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.9/147.9 kB 2.9 MB/s eta 0:00:00
Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.9/99.9 kB 1.9 MB/s eta 0:00:00
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Using cached idna-3.7-py3-none-any.whl (66 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.7/144.7 kB 2.9 MB/s eta 0:00:00
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Downloading selenium-4.20.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 32.0 MB/s eta 0:00:00
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached trio-0.25.0-py3-none-any.whl (467 kB)
Using cached trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Downloading websockets-12.0-cp311-cp311-win_amd64.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 2.4 MB/s eta 0:00:00
Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Downloading cffi-1.16.0-cp311-cp311-win_amd64.whl (181 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.5/181.5 kB 3.7 MB/s eta 0:00:00
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: undetected-chromedriver
  Building wheel for undetected-chromedriver (pyproject.toml) ... done
  Created wheel for undetected-chromedriver: filename=undetected_chromedriver-3.5.5-py3-none-any.whl size=47130 sha256=42522517979901207a74e582eccd49f5ed98727c0a2130d9284a34a923237473
  Stored in directory: c:\users\shedowe\appdata\local\pip\cache\wheels\5c\b9\03\4b6e38f019d6170e8c25df2e1e362d7bdf9ff4012df2dc85c0
Successfully built undetected-chromedriver
Installing collected packages: sortedcontainers, websockets, urllib3, typing-extensions, soupsieve, sniffio, pyyaml, pysocks, pycparser, idna, h11, charset-normalizer, certifi, attrs, wsproto, requests, outcome, cffi, beautifulsoup4, trio, trio-websocket, selenium, undetected-chromedriver
Successfully installed attrs-23.2.0 beautifulsoup4-4.12.3 certifi-2024.2.2 cffi-1.16.0 charset-normalizer-3.3.2 h11-0.14.0 idna-3.7 outcome-1.3.0.post0 pycparser-2.22 pysocks-1.7.1 pyyaml-6.0.1 requests-2.31.0 selenium-4.20.0 sniffio-1.3.1 sortedcontainers-2.4.0 soupsieve-2.5 trio-0.25.0 trio-websocket-0.11.1 typing-extensions-4.11.0 undetected-chromedriver-3.5.5 urllib3-2.2.1 websockets-12.0 wsproto-1.2.0

(venv) C:\Users\Shedowe\Downloads\Compressed\series-scraper-main>python main.py serie https://bs.to/serie/Pok-mon-Horizons-The-Series-Pokemon-2023 Deutsch
INFO - 2024-04-29 19:20:25,194 - main.py -> ------------- Series-Scraper started ------------
INFO - 2024-04-29 19:20:25,404 - main.py -> Season 1 has 47 Episodes.
Traceback (most recent call last):
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\main.py", line 47, in check_episodes
    episode_link = get_episode_link(url, language, provider, season, episode, burning_series)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\src\html_scraper.py", line 37, in get_episode_link
    link_to_episode = find_bs_link_to_episode(link_to_episode, provider)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\src\html_scraper.py", line 105, in find_bs_link_to_episode
    video_in_media_provider = WebDriverWait(driver, 0).until(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00F0C113+48259]
        (No symbol) [0x00E9CA41]
        (No symbol) [0x00D90A17]
        (No symbol) [0x00DD0BED]
        (No symbol) [0x00DD0C9B]
        (No symbol) [0x00E0BC12]
        (No symbol) [0x00DF0DE4]
        (No symbol) [0x00E09B9C]
        (No symbol) [0x00DF0B36]
        (No symbol) [0x00DC570D]
        (No symbol) [0x00DC62CD]
        GetHandleVerifier [0x011C6533+2908323]
        GetHandleVerifier [0x01203B4B+3159739]
        GetHandleVerifier [0x00FA505B+674763]
        GetHandleVerifier [0x00FAB21C+699788]
        (No symbol) [0x00EA6244]
        (No symbol) [0x00EA2298]
        (No symbol) [0x00EA242C]
        (No symbol) [0x00E94BB0]
        BaseThreadInitThunk [0x75927BA9+25]
        RtlInitializeExceptionChain [0x7720BE3B+107]
        RtlClearBits [0x7720BDBF+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\main.py", line 127, in <module>
    main()
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\main.py", line 100, in main
    pending_episodes, language_episodes, future_list = check_episodes(
                                                       ^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\main.py", line 54, in check_episodes
    except [HTTPError, URLError] as message:
TypeError: catching classes that do not inherit from BaseException is not allowed
Exception ignored in: <function Chrome.__del__ at 0x000001BDC2FAD9E0>
Traceback (most recent call last):
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] Das Handle ist ungültig

(venv) C:\Users\Shedowe\Downloads\Compressed\series-scraper-main>

**Comment by speedyconzales** [comment]
`python --version` output in the venv?

**Comment by shedowe19** [comment]
(venv) C:\Users\Shedowe\Downloads\Compressed\series-scraper-main>python --version
Python 3.11.9

**Comment by speedyconzales** [comment]
actually it is an oversight on my end. will fix it immediately, but python3.11 was needed nevertheless
