### ISSUE TITLE
[Feature] Series as following schema S01E01.mp4

### ISSUE THREAD

**Issue by shedowe19** [speedyconzales/series-scraper#5]
I will save the Series as following schema S01E01.mp4 and not all other names as s01e01 - Deutsch i dont need this.

Can you explain me how can edit this?

now the Downloader Works.

**Comment by speedyconzales** [comment]
have a look at https://github.com/speedyconzales/series-scraper/blob/e6e9032183e93f26d5ed338b48badf2053c90472/main.py#L42

**Comment by shedowe19** [comment]
Can you send me the right code for S01E01.mp4 

and the Seanson 01 should Named to Staffel 01

**Comment by shedowe19** [comment]
Okay forgot.

I have find out how can get.

Thanks for Helping and add Support for bs.to
