### ISSUE TITLE
Captcha Plugin for Chrome Automatic Resolver for Captchas

### ISSUE THREAD

**Issue by shedowe19** [speedyconzales/series-scraper#6]
https://chromewebstore.google.com/detail/captcha-solver-auto-hcapt/hlifkpholllijblknnmbfagnkjneagid?utm_source=ext_app_menu

Can i add extensions to the Browser that is always there?

This is auto reCapcha resolver

**Comment by shedowe19** [comment]
This Worked with bs.to

**Comment by speedyconzales** [comment]
I will have a look. already thought about adding this

**Comment by speedyconzales** [comment]
with #8 on its way I do not think that this is possible due to https://stackoverflow.com/questions/75909838/trying-to-use-extension-in-seleniumbase

**Comment by shedowe19** [comment]
with SB(uc=True, headless=False, extension_dir=r"B:\Users\Admin\Downloads\Compressed\series-scraper-feature-selenium-base\Extensions\13c3bb8f-e454-419b-b364-9f01572faa98") as sb:

This will work

and now is automated

**Comment by shedowe19** [comment]
unpacked extension worked

**Comment by shedowe19** [comment]
Now the headless Mode function Perfectly

**Comment by speedyconzales** [comment]
Glad it works then, although it is more and more preparation work, which I don't like. I will think about a solution that just works.
