### ISSUE TITLE
Chrome does not Close correctly after Downloading

### ISSUE THREAD

**Issue by shedowe19** [speedyconzales/series-scraper#7]
The Chrome exes does not closing after the Download is finished.

The UI is no more shown, this is good but not closing and this is in background and eating 2 % per chrome exex permanently

Can you look on this issue

**Comment by speedyconzales** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1270
for now it is there. until I will make the change from undetected-chromedriver to seleniumbase in the future

**Comment by speedyconzales** [comment]
@shedowe19 can you have a look at #8 and confirm that it solves this issue

**Comment by shedowe19** [comment]
This is now resolved.

Thanks
